'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34014
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PROLozanoJavier.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _297_Volkswagen_Phaeton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("297-Volkswagen-Phaeton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_a8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-a8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_q1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-q1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_q2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-q2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_q3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-q3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_q7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-q7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_quattro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-quattro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_r8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-r8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_rs6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-rs6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property audi_tt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi-tt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property car_wire_high() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("car_wire_high", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_ax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-ax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_berlingo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-berlingo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_bx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-bx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property citroen_c8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen-c8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cliente_satisfecho2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cliente satisfecho2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fabia_combi_side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fabia-combi-side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fabia2015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fabia2015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fabia20151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fabia20151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grey_triangles_background_23_2147494297() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey-triangles-background_23-2147494297", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ibiza_st() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ibiza_st", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_carens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-carens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_carnival() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-carnival", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_ceed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-ceed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_picanto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-picanto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_rio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-rio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_sorento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-sorento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_soul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-soul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_sportage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-sportage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kia_venga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kia-venga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pastillas_de_frenos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pastillas-de-frenos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_alhambra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat-alhambra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_alhambra1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat-alhambra1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_cordoba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_cordoba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_cupra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_cupra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_ibiza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_ibiza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SEAT_Leon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEAT-Leon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_leon_st() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat-leon-st", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seat_mii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat-mii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SEAT_Toledo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEAT-Toledo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_citigo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-citigo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_fabia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-fabia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_favorit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-favorit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_octavia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-octavia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_octavia_wagon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda_octavia_wagon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_rapid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-rapid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_scout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda scout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_superb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda-superb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skoda_yeti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skoda yeti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Superb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Superb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property touran() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("touran", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_cc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen-cc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_eos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen eos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_golf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen-golf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_jetta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen-jetta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_polo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen-polo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property volkswagen_tiguan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volkswagen-tiguan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vw_beetle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vw beetle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vw_golf_variant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vw_golf_variant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vw_passat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vw_passat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yeti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yeti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
